-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PAYMENT';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'MASTERCLASS';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'OTHER';
